[package]
name = "r53up"
version = "0.1.0"
authors = ["Ferruccio Barletta <ferruccio.barletta@gmail.com>"]
description = "Update Route 53 record for EC2 instance"

[dependencies]
quick-error = "1.2.2"
rusoto_core = "0.35.0"
rusoto_route53 = "0.35.0"
reqwest = "0.9.5"
clap = "2.32.0"
