[package]
name = "r53up"
version = "0.1.0"
authors = ["Ferruccio Barletta <ferruccio.barletta@gmail.com>"]

[dependencies]
quick-error = "1.2.2"
rusoto_core = "0.32.0"
rusoto_route53 = "0.32.0"
reqwest = "0.8.6"
clap = "2.31.2"
